//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AffirmMedicalMainPortal
{
    using System;
    using System.Collections.Generic;
    using AffirmMedicalMainPortal.Components;
    
    public partial class account : BaseModel
    {
        private string _listID;
    	public string ListID 
    	{ 
    		get { return _listID; } 
    		set { SetProperty(ref _listID, value); } 
    	}
    
        private string _timeCreated;
    	public string TimeCreated 
    	{ 
    		get { return _timeCreated; } 
    		set { SetProperty(ref _timeCreated, value); } 
    	}
    
        private string _timeModified;
    	public string TimeModified 
    	{ 
    		get { return _timeModified; } 
    		set { SetProperty(ref _timeModified, value); } 
    	}
    
        private string _editSequence;
    	public string EditSequence 
    	{ 
    		get { return _editSequence; } 
    		set { SetProperty(ref _editSequence, value); } 
    	}
    
        private string _name;
    	public string Name 
    	{ 
    		get { return _name; } 
    		set { SetProperty(ref _name, value); } 
    	}
    
        private string _fullName;
    	public string FullName 
    	{ 
    		get { return _fullName; } 
    		set { SetProperty(ref _fullName, value); } 
    	}
    
        private string _isActive;
    	public string IsActive 
    	{ 
    		get { return _isActive; } 
    		set { SetProperty(ref _isActive, value); } 
    	}
    
        private string _parentRef_ListID;
    	public string ParentRef_ListID 
    	{ 
    		get { return _parentRef_ListID; } 
    		set { SetProperty(ref _parentRef_ListID, value); } 
    	}
    
        private string _parentRef_FullName;
    	public string ParentRef_FullName 
    	{ 
    		get { return _parentRef_FullName; } 
    		set { SetProperty(ref _parentRef_FullName, value); } 
    	}
    
        private Nullable<int> _sublevel;
    	public Nullable<int> Sublevel 
    	{ 
    		get { return _sublevel; } 
    		set { SetProperty(ref _sublevel, value); } 
    	}
    
        private string _accountType;
    	public string AccountType 
    	{ 
    		get { return _accountType; } 
    		set { SetProperty(ref _accountType, value); } 
    	}
    
        private string _detailAccountType;
    	public string DetailAccountType 
    	{ 
    		get { return _detailAccountType; } 
    		set { SetProperty(ref _detailAccountType, value); } 
    	}
    
        private string _accountNumber;
    	public string AccountNumber 
    	{ 
    		get { return _accountNumber; } 
    		set { SetProperty(ref _accountNumber, value); } 
    	}
    
        private string _bankNumber;
    	public string BankNumber 
    	{ 
    		get { return _bankNumber; } 
    		set { SetProperty(ref _bankNumber, value); } 
    	}
    
        private string _lastCheckNumber;
    	public string LastCheckNumber 
    	{ 
    		get { return _lastCheckNumber; } 
    		set { SetProperty(ref _lastCheckNumber, value); } 
    	}
    
        private string _description;
    	public string Description 
    	{ 
    		get { return _description; } 
    		set { SetProperty(ref _description, value); } 
    	}
    
        private Nullable<decimal> _balance;
    	public Nullable<decimal> Balance 
    	{ 
    		get { return _balance; } 
    		set { SetProperty(ref _balance, value); } 
    	}
    
        private Nullable<decimal> _totalBalance;
    	public Nullable<decimal> TotalBalance 
    	{ 
    		get { return _totalBalance; } 
    		set { SetProperty(ref _totalBalance, value); } 
    	}
    
        private string _cashFlowClassification;
    	public string CashFlowClassification 
    	{ 
    		get { return _cashFlowClassification; } 
    		set { SetProperty(ref _cashFlowClassification, value); } 
    	}
    
        private string _specialAccountType;
    	public string SpecialAccountType 
    	{ 
    		get { return _specialAccountType; } 
    		set { SetProperty(ref _specialAccountType, value); } 
    	}
    
        private string _salesTaxCodeRef_ListID;
    	public string SalesTaxCodeRef_ListID 
    	{ 
    		get { return _salesTaxCodeRef_ListID; } 
    		set { SetProperty(ref _salesTaxCodeRef_ListID, value); } 
    	}
    
        private string _salesTaxCodeRef_FullName;
    	public string SalesTaxCodeRef_FullName 
    	{ 
    		get { return _salesTaxCodeRef_FullName; } 
    		set { SetProperty(ref _salesTaxCodeRef_FullName, value); } 
    	}
    
        private string _isTaxAccount;
    	public string IsTaxAccount 
    	{ 
    		get { return _isTaxAccount; } 
    		set { SetProperty(ref _isTaxAccount, value); } 
    	}
    
        private Nullable<int> _taxLineID;
    	public Nullable<int> TaxLineID 
    	{ 
    		get { return _taxLineID; } 
    		set { SetProperty(ref _taxLineID, value); } 
    	}
    
        private string _taxLineInfo;
    	public string TaxLineInfo 
    	{ 
    		get { return _taxLineInfo; } 
    		set { SetProperty(ref _taxLineInfo, value); } 
    	}
    
        private string _currencyRef_ListID;
    	public string CurrencyRef_ListID 
    	{ 
    		get { return _currencyRef_ListID; } 
    		set { SetProperty(ref _currencyRef_ListID, value); } 
    	}
    
        private string _currencyRef_FullName;
    	public string CurrencyRef_FullName 
    	{ 
    		get { return _currencyRef_FullName; } 
    		set { SetProperty(ref _currencyRef_FullName, value); } 
    	}
    
        private string _customField1;
    	public string CustomField1 
    	{ 
    		get { return _customField1; } 
    		set { SetProperty(ref _customField1, value); } 
    	}
    
        private string _customField2;
    	public string CustomField2 
    	{ 
    		get { return _customField2; } 
    		set { SetProperty(ref _customField2, value); } 
    	}
    
        private string _customField3;
    	public string CustomField3 
    	{ 
    		get { return _customField3; } 
    		set { SetProperty(ref _customField3, value); } 
    	}
    
        private string _customField4;
    	public string CustomField4 
    	{ 
    		get { return _customField4; } 
    		set { SetProperty(ref _customField4, value); } 
    	}
    
        private string _customField5;
    	public string CustomField5 
    	{ 
    		get { return _customField5; } 
    		set { SetProperty(ref _customField5, value); } 
    	}
    
        private string _customField6;
    	public string CustomField6 
    	{ 
    		get { return _customField6; } 
    		set { SetProperty(ref _customField6, value); } 
    	}
    
        private string _customField7;
    	public string CustomField7 
    	{ 
    		get { return _customField7; } 
    		set { SetProperty(ref _customField7, value); } 
    	}
    
        private string _customField8;
    	public string CustomField8 
    	{ 
    		get { return _customField8; } 
    		set { SetProperty(ref _customField8, value); } 
    	}
    
        private string _customField9;
    	public string CustomField9 
    	{ 
    		get { return _customField9; } 
    		set { SetProperty(ref _customField9, value); } 
    	}
    
        private string _customField10;
    	public string CustomField10 
    	{ 
    		get { return _customField10; } 
    		set { SetProperty(ref _customField10, value); } 
    	}
    
        private string _customField11;
    	public string CustomField11 
    	{ 
    		get { return _customField11; } 
    		set { SetProperty(ref _customField11, value); } 
    	}
    
        private string _customField12;
    	public string CustomField12 
    	{ 
    		get { return _customField12; } 
    		set { SetProperty(ref _customField12, value); } 
    	}
    
        private string _customField13;
    	public string CustomField13 
    	{ 
    		get { return _customField13; } 
    		set { SetProperty(ref _customField13, value); } 
    	}
    
        private string _customField14;
    	public string CustomField14 
    	{ 
    		get { return _customField14; } 
    		set { SetProperty(ref _customField14, value); } 
    	}
    
        private string _customField15;
    	public string CustomField15 
    	{ 
    		get { return _customField15; } 
    		set { SetProperty(ref _customField15, value); } 
    	}
    
        private string _status;
    	public string Status 
    	{ 
    		get { return _status; } 
    		set { SetProperty(ref _status, value); } 
    	}
    
    }
}
