//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AffirmMedicalMainPortal
{
    using System;
    using System.Collections.Generic;
    using AffirmMedicalMainPortal.Components;
    
    public partial class company : BaseModel
    {
        private string _isSampleCompany;
    	public string IsSampleCompany 
    	{ 
    		get { return _isSampleCompany; } 
    		set { SetProperty(ref _isSampleCompany, value); } 
    	}
    
        private string _companyName;
    	public string CompanyName 
    	{ 
    		get { return _companyName; } 
    		set { SetProperty(ref _companyName, value); } 
    	}
    
        private string _legalCompanyName;
    	public string LegalCompanyName 
    	{ 
    		get { return _legalCompanyName; } 
    		set { SetProperty(ref _legalCompanyName, value); } 
    	}
    
        private string _address_Addr1;
    	public string Address_Addr1 
    	{ 
    		get { return _address_Addr1; } 
    		set { SetProperty(ref _address_Addr1, value); } 
    	}
    
        private string _address_Addr2;
    	public string Address_Addr2 
    	{ 
    		get { return _address_Addr2; } 
    		set { SetProperty(ref _address_Addr2, value); } 
    	}
    
        private string _address_Addr3;
    	public string Address_Addr3 
    	{ 
    		get { return _address_Addr3; } 
    		set { SetProperty(ref _address_Addr3, value); } 
    	}
    
        private string _address_Addr4;
    	public string Address_Addr4 
    	{ 
    		get { return _address_Addr4; } 
    		set { SetProperty(ref _address_Addr4, value); } 
    	}
    
        private string _address_Addr5;
    	public string Address_Addr5 
    	{ 
    		get { return _address_Addr5; } 
    		set { SetProperty(ref _address_Addr5, value); } 
    	}
    
        private string _address_City;
    	public string Address_City 
    	{ 
    		get { return _address_City; } 
    		set { SetProperty(ref _address_City, value); } 
    	}
    
        private string _address_State;
    	public string Address_State 
    	{ 
    		get { return _address_State; } 
    		set { SetProperty(ref _address_State, value); } 
    	}
    
        private string _address_PostalCode;
    	public string Address_PostalCode 
    	{ 
    		get { return _address_PostalCode; } 
    		set { SetProperty(ref _address_PostalCode, value); } 
    	}
    
        private string _address_Country;
    	public string Address_Country 
    	{ 
    		get { return _address_Country; } 
    		set { SetProperty(ref _address_Country, value); } 
    	}
    
        private string _address_Note;
    	public string Address_Note 
    	{ 
    		get { return _address_Note; } 
    		set { SetProperty(ref _address_Note, value); } 
    	}
    
        private string _legalAddress_Addr1;
    	public string LegalAddress_Addr1 
    	{ 
    		get { return _legalAddress_Addr1; } 
    		set { SetProperty(ref _legalAddress_Addr1, value); } 
    	}
    
        private string _legalAddress_Addr2;
    	public string LegalAddress_Addr2 
    	{ 
    		get { return _legalAddress_Addr2; } 
    		set { SetProperty(ref _legalAddress_Addr2, value); } 
    	}
    
        private string _legalAddress_Addr3;
    	public string LegalAddress_Addr3 
    	{ 
    		get { return _legalAddress_Addr3; } 
    		set { SetProperty(ref _legalAddress_Addr3, value); } 
    	}
    
        private string _legalAddress_Addr4;
    	public string LegalAddress_Addr4 
    	{ 
    		get { return _legalAddress_Addr4; } 
    		set { SetProperty(ref _legalAddress_Addr4, value); } 
    	}
    
        private string _legalAddress_Addr5;
    	public string LegalAddress_Addr5 
    	{ 
    		get { return _legalAddress_Addr5; } 
    		set { SetProperty(ref _legalAddress_Addr5, value); } 
    	}
    
        private string _legalAddress_City;
    	public string LegalAddress_City 
    	{ 
    		get { return _legalAddress_City; } 
    		set { SetProperty(ref _legalAddress_City, value); } 
    	}
    
        private string _legalAddress_State;
    	public string LegalAddress_State 
    	{ 
    		get { return _legalAddress_State; } 
    		set { SetProperty(ref _legalAddress_State, value); } 
    	}
    
        private string _legalAddress_PostalCode;
    	public string LegalAddress_PostalCode 
    	{ 
    		get { return _legalAddress_PostalCode; } 
    		set { SetProperty(ref _legalAddress_PostalCode, value); } 
    	}
    
        private string _legalAddress_Country;
    	public string LegalAddress_Country 
    	{ 
    		get { return _legalAddress_Country; } 
    		set { SetProperty(ref _legalAddress_Country, value); } 
    	}
    
        private string _legalAddress_Note;
    	public string LegalAddress_Note 
    	{ 
    		get { return _legalAddress_Note; } 
    		set { SetProperty(ref _legalAddress_Note, value); } 
    	}
    
        private string _companyAddressForCustomer_Addr1;
    	public string CompanyAddressForCustomer_Addr1 
    	{ 
    		get { return _companyAddressForCustomer_Addr1; } 
    		set { SetProperty(ref _companyAddressForCustomer_Addr1, value); } 
    	}
    
        private string _companyAddressForCustomer_Addr2;
    	public string CompanyAddressForCustomer_Addr2 
    	{ 
    		get { return _companyAddressForCustomer_Addr2; } 
    		set { SetProperty(ref _companyAddressForCustomer_Addr2, value); } 
    	}
    
        private string _companyAddressForCustomer_Addr3;
    	public string CompanyAddressForCustomer_Addr3 
    	{ 
    		get { return _companyAddressForCustomer_Addr3; } 
    		set { SetProperty(ref _companyAddressForCustomer_Addr3, value); } 
    	}
    
        private string _companyAddressForCustomer_Addr4;
    	public string CompanyAddressForCustomer_Addr4 
    	{ 
    		get { return _companyAddressForCustomer_Addr4; } 
    		set { SetProperty(ref _companyAddressForCustomer_Addr4, value); } 
    	}
    
        private string _companyAddressForCustomer_Addr5;
    	public string CompanyAddressForCustomer_Addr5 
    	{ 
    		get { return _companyAddressForCustomer_Addr5; } 
    		set { SetProperty(ref _companyAddressForCustomer_Addr5, value); } 
    	}
    
        private string _companyAddressForCustomer_City;
    	public string CompanyAddressForCustomer_City 
    	{ 
    		get { return _companyAddressForCustomer_City; } 
    		set { SetProperty(ref _companyAddressForCustomer_City, value); } 
    	}
    
        private string _companyAddressForCustomer_State;
    	public string CompanyAddressForCustomer_State 
    	{ 
    		get { return _companyAddressForCustomer_State; } 
    		set { SetProperty(ref _companyAddressForCustomer_State, value); } 
    	}
    
        private string _companyAddressForCustomer_PostalCode;
    	public string CompanyAddressForCustomer_PostalCode 
    	{ 
    		get { return _companyAddressForCustomer_PostalCode; } 
    		set { SetProperty(ref _companyAddressForCustomer_PostalCode, value); } 
    	}
    
        private string _companyAddressForCustomer_Country;
    	public string CompanyAddressForCustomer_Country 
    	{ 
    		get { return _companyAddressForCustomer_Country; } 
    		set { SetProperty(ref _companyAddressForCustomer_Country, value); } 
    	}
    
        private string _companyAddressForCustomer_Note;
    	public string CompanyAddressForCustomer_Note 
    	{ 
    		get { return _companyAddressForCustomer_Note; } 
    		set { SetProperty(ref _companyAddressForCustomer_Note, value); } 
    	}
    
        private string _phone;
    	public string Phone 
    	{ 
    		get { return _phone; } 
    		set { SetProperty(ref _phone, value); } 
    	}
    
        private string _fax;
    	public string Fax 
    	{ 
    		get { return _fax; } 
    		set { SetProperty(ref _fax, value); } 
    	}
    
        private string _email;
    	public string Email 
    	{ 
    		get { return _email; } 
    		set { SetProperty(ref _email, value); } 
    	}
    
        private string _companyEmailForCustomer;
    	public string CompanyEmailForCustomer 
    	{ 
    		get { return _companyEmailForCustomer; } 
    		set { SetProperty(ref _companyEmailForCustomer, value); } 
    	}
    
        private string _companyWebSite;
    	public string CompanyWebSite 
    	{ 
    		get { return _companyWebSite; } 
    		set { SetProperty(ref _companyWebSite, value); } 
    	}
    
        private string _firstMonthFiscalYear;
    	public string FirstMonthFiscalYear 
    	{ 
    		get { return _firstMonthFiscalYear; } 
    		set { SetProperty(ref _firstMonthFiscalYear, value); } 
    	}
    
        private string _firstMonthIncomeTaxYear;
    	public string FirstMonthIncomeTaxYear 
    	{ 
    		get { return _firstMonthIncomeTaxYear; } 
    		set { SetProperty(ref _firstMonthIncomeTaxYear, value); } 
    	}
    
        private string _companyType;
    	public string CompanyType 
    	{ 
    		get { return _companyType; } 
    		set { SetProperty(ref _companyType, value); } 
    	}
    
        private string _eIN;
    	public string EIN 
    	{ 
    		get { return _eIN; } 
    		set { SetProperty(ref _eIN, value); } 
    	}
    
        private string _taxForm;
    	public string TaxForm 
    	{ 
    		get { return _taxForm; } 
    		set { SetProperty(ref _taxForm, value); } 
    	}
    
        private string _customField1;
    	public string CustomField1 
    	{ 
    		get { return _customField1; } 
    		set { SetProperty(ref _customField1, value); } 
    	}
    
        private string _customField2;
    	public string CustomField2 
    	{ 
    		get { return _customField2; } 
    		set { SetProperty(ref _customField2, value); } 
    	}
    
        private string _customField3;
    	public string CustomField3 
    	{ 
    		get { return _customField3; } 
    		set { SetProperty(ref _customField3, value); } 
    	}
    
        private string _customField4;
    	public string CustomField4 
    	{ 
    		get { return _customField4; } 
    		set { SetProperty(ref _customField4, value); } 
    	}
    
        private string _customField5;
    	public string CustomField5 
    	{ 
    		get { return _customField5; } 
    		set { SetProperty(ref _customField5, value); } 
    	}
    
        private string _customField6;
    	public string CustomField6 
    	{ 
    		get { return _customField6; } 
    		set { SetProperty(ref _customField6, value); } 
    	}
    
        private string _customField7;
    	public string CustomField7 
    	{ 
    		get { return _customField7; } 
    		set { SetProperty(ref _customField7, value); } 
    	}
    
        private string _customField8;
    	public string CustomField8 
    	{ 
    		get { return _customField8; } 
    		set { SetProperty(ref _customField8, value); } 
    	}
    
        private string _customField9;
    	public string CustomField9 
    	{ 
    		get { return _customField9; } 
    		set { SetProperty(ref _customField9, value); } 
    	}
    
        private string _customField10;
    	public string CustomField10 
    	{ 
    		get { return _customField10; } 
    		set { SetProperty(ref _customField10, value); } 
    	}
    
        private string _customField11;
    	public string CustomField11 
    	{ 
    		get { return _customField11; } 
    		set { SetProperty(ref _customField11, value); } 
    	}
    
        private string _customField12;
    	public string CustomField12 
    	{ 
    		get { return _customField12; } 
    		set { SetProperty(ref _customField12, value); } 
    	}
    
        private string _customField13;
    	public string CustomField13 
    	{ 
    		get { return _customField13; } 
    		set { SetProperty(ref _customField13, value); } 
    	}
    
        private string _customField14;
    	public string CustomField14 
    	{ 
    		get { return _customField14; } 
    		set { SetProperty(ref _customField14, value); } 
    	}
    
        private string _customField15;
    	public string CustomField15 
    	{ 
    		get { return _customField15; } 
    		set { SetProperty(ref _customField15, value); } 
    	}
    
        private string _status;
    	public string Status 
    	{ 
    		get { return _status; } 
    		set { SetProperty(ref _status, value); } 
    	}
    
        private int _companyID;
    	public int CompanyID 
    	{ 
    		get { return _companyID; } 
    		set { SetProperty(ref _companyID, value); } 
    	}
    
    }
}
