//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AffirmMedicalMainPortal
{
    using System;
    using System.Collections.Generic;
    using AffirmMedicalMainPortal.Components;
    
    public partial class customer : BaseModel
    {
        private string _listID;
    	public string ListID 
    	{ 
    		get { return _listID; } 
    		set { SetProperty(ref _listID, value); } 
    	}
    
        private string _timeCreated;
    	public string TimeCreated 
    	{ 
    		get { return _timeCreated; } 
    		set { SetProperty(ref _timeCreated, value); } 
    	}
    
        private string _timeModified;
    	public string TimeModified 
    	{ 
    		get { return _timeModified; } 
    		set { SetProperty(ref _timeModified, value); } 
    	}
    
        private string _editSequence;
    	public string EditSequence 
    	{ 
    		get { return _editSequence; } 
    		set { SetProperty(ref _editSequence, value); } 
    	}
    
        private string _name;
    	public string Name 
    	{ 
    		get { return _name; } 
    		set { SetProperty(ref _name, value); } 
    	}
    
        private string _fullName;
    	public string FullName 
    	{ 
    		get { return _fullName; } 
    		set { SetProperty(ref _fullName, value); } 
    	}
    
        private string _isActive;
    	public string IsActive 
    	{ 
    		get { return _isActive; } 
    		set { SetProperty(ref _isActive, value); } 
    	}
    
        private string _classRef_ListID;
    	public string ClassRef_ListID 
    	{ 
    		get { return _classRef_ListID; } 
    		set { SetProperty(ref _classRef_ListID, value); } 
    	}
    
        private string _classRef_FullName;
    	public string ClassRef_FullName 
    	{ 
    		get { return _classRef_FullName; } 
    		set { SetProperty(ref _classRef_FullName, value); } 
    	}
    
        private string _parentRef_ListID;
    	public string ParentRef_ListID 
    	{ 
    		get { return _parentRef_ListID; } 
    		set { SetProperty(ref _parentRef_ListID, value); } 
    	}
    
        private string _parentRef_FullName;
    	public string ParentRef_FullName 
    	{ 
    		get { return _parentRef_FullName; } 
    		set { SetProperty(ref _parentRef_FullName, value); } 
    	}
    
        private Nullable<int> _sublevel;
    	public Nullable<int> Sublevel 
    	{ 
    		get { return _sublevel; } 
    		set { SetProperty(ref _sublevel, value); } 
    	}
    
        private string _companyName;
    	public string CompanyName 
    	{ 
    		get { return _companyName; } 
    		set { SetProperty(ref _companyName, value); } 
    	}
    
        private string _salutation;
    	public string Salutation 
    	{ 
    		get { return _salutation; } 
    		set { SetProperty(ref _salutation, value); } 
    	}
    
        private string _firstName;
    	public string FirstName 
    	{ 
    		get { return _firstName; } 
    		set { SetProperty(ref _firstName, value); } 
    	}
    
        private string _middleName;
    	public string MiddleName 
    	{ 
    		get { return _middleName; } 
    		set { SetProperty(ref _middleName, value); } 
    	}
    
        private string _lastName;
    	public string LastName 
    	{ 
    		get { return _lastName; } 
    		set { SetProperty(ref _lastName, value); } 
    	}
    
        private string _suffix;
    	public string Suffix 
    	{ 
    		get { return _suffix; } 
    		set { SetProperty(ref _suffix, value); } 
    	}
    
        private string _billAddress_Addr1;
    	public string BillAddress_Addr1 
    	{ 
    		get { return _billAddress_Addr1; } 
    		set { SetProperty(ref _billAddress_Addr1, value); } 
    	}
    
        private string _billAddress_Addr2;
    	public string BillAddress_Addr2 
    	{ 
    		get { return _billAddress_Addr2; } 
    		set { SetProperty(ref _billAddress_Addr2, value); } 
    	}
    
        private string _billAddress_Addr3;
    	public string BillAddress_Addr3 
    	{ 
    		get { return _billAddress_Addr3; } 
    		set { SetProperty(ref _billAddress_Addr3, value); } 
    	}
    
        private string _billAddress_Addr4;
    	public string BillAddress_Addr4 
    	{ 
    		get { return _billAddress_Addr4; } 
    		set { SetProperty(ref _billAddress_Addr4, value); } 
    	}
    
        private string _billAddress_Addr5;
    	public string BillAddress_Addr5 
    	{ 
    		get { return _billAddress_Addr5; } 
    		set { SetProperty(ref _billAddress_Addr5, value); } 
    	}
    
        private string _billAddress_City;
    	public string BillAddress_City 
    	{ 
    		get { return _billAddress_City; } 
    		set { SetProperty(ref _billAddress_City, value); } 
    	}
    
        private string _billAddress_State;
    	public string BillAddress_State 
    	{ 
    		get { return _billAddress_State; } 
    		set { SetProperty(ref _billAddress_State, value); } 
    	}
    
        private string _billAddress_PostalCode;
    	public string BillAddress_PostalCode 
    	{ 
    		get { return _billAddress_PostalCode; } 
    		set { SetProperty(ref _billAddress_PostalCode, value); } 
    	}
    
        private string _billAddress_Country;
    	public string BillAddress_Country 
    	{ 
    		get { return _billAddress_Country; } 
    		set { SetProperty(ref _billAddress_Country, value); } 
    	}
    
        private string _billAddress_Note;
    	public string BillAddress_Note 
    	{ 
    		get { return _billAddress_Note; } 
    		set { SetProperty(ref _billAddress_Note, value); } 
    	}
    
        private string _shipAddress_Addr1;
    	public string ShipAddress_Addr1 
    	{ 
    		get { return _shipAddress_Addr1; } 
    		set { SetProperty(ref _shipAddress_Addr1, value); } 
    	}
    
        private string _shipAddress_Addr2;
    	public string ShipAddress_Addr2 
    	{ 
    		get { return _shipAddress_Addr2; } 
    		set { SetProperty(ref _shipAddress_Addr2, value); } 
    	}
    
        private string _shipAddress_Addr3;
    	public string ShipAddress_Addr3 
    	{ 
    		get { return _shipAddress_Addr3; } 
    		set { SetProperty(ref _shipAddress_Addr3, value); } 
    	}
    
        private string _shipAddress_Addr4;
    	public string ShipAddress_Addr4 
    	{ 
    		get { return _shipAddress_Addr4; } 
    		set { SetProperty(ref _shipAddress_Addr4, value); } 
    	}
    
        private string _shipAddress_Addr5;
    	public string ShipAddress_Addr5 
    	{ 
    		get { return _shipAddress_Addr5; } 
    		set { SetProperty(ref _shipAddress_Addr5, value); } 
    	}
    
        private string _shipAddress_City;
    	public string ShipAddress_City 
    	{ 
    		get { return _shipAddress_City; } 
    		set { SetProperty(ref _shipAddress_City, value); } 
    	}
    
        private string _shipAddress_State;
    	public string ShipAddress_State 
    	{ 
    		get { return _shipAddress_State; } 
    		set { SetProperty(ref _shipAddress_State, value); } 
    	}
    
        private string _shipAddress_PostalCode;
    	public string ShipAddress_PostalCode 
    	{ 
    		get { return _shipAddress_PostalCode; } 
    		set { SetProperty(ref _shipAddress_PostalCode, value); } 
    	}
    
        private string _shipAddress_Country;
    	public string ShipAddress_Country 
    	{ 
    		get { return _shipAddress_Country; } 
    		set { SetProperty(ref _shipAddress_Country, value); } 
    	}
    
        private string _shipAddress_Note;
    	public string ShipAddress_Note 
    	{ 
    		get { return _shipAddress_Note; } 
    		set { SetProperty(ref _shipAddress_Note, value); } 
    	}
    
        private string _printAs;
    	public string PrintAs 
    	{ 
    		get { return _printAs; } 
    		set { SetProperty(ref _printAs, value); } 
    	}
    
        private string _phone;
    	public string Phone 
    	{ 
    		get { return _phone; } 
    		set { SetProperty(ref _phone, value); } 
    	}
    
        private string _mobile;
    	public string Mobile 
    	{ 
    		get { return _mobile; } 
    		set { SetProperty(ref _mobile, value); } 
    	}
    
        private string _pager;
    	public string Pager 
    	{ 
    		get { return _pager; } 
    		set { SetProperty(ref _pager, value); } 
    	}
    
        private string _altPhone;
    	public string AltPhone 
    	{ 
    		get { return _altPhone; } 
    		set { SetProperty(ref _altPhone, value); } 
    	}
    
        private string _fax;
    	public string Fax 
    	{ 
    		get { return _fax; } 
    		set { SetProperty(ref _fax, value); } 
    	}
    
        private string _email;
    	public string Email 
    	{ 
    		get { return _email; } 
    		set { SetProperty(ref _email, value); } 
    	}
    
        private string _cc;
    	public string Cc 
    	{ 
    		get { return _cc; } 
    		set { SetProperty(ref _cc, value); } 
    	}
    
        private string _contact;
    	public string Contact 
    	{ 
    		get { return _contact; } 
    		set { SetProperty(ref _contact, value); } 
    	}
    
        private string _altContact;
    	public string AltContact 
    	{ 
    		get { return _altContact; } 
    		set { SetProperty(ref _altContact, value); } 
    	}
    
        private string _customerTypeRef_ListID;
    	public string CustomerTypeRef_ListID 
    	{ 
    		get { return _customerTypeRef_ListID; } 
    		set { SetProperty(ref _customerTypeRef_ListID, value); } 
    	}
    
        private string _customerTypeRef_FullName;
    	public string CustomerTypeRef_FullName 
    	{ 
    		get { return _customerTypeRef_FullName; } 
    		set { SetProperty(ref _customerTypeRef_FullName, value); } 
    	}
    
        private string _termsRef_ListID;
    	public string TermsRef_ListID 
    	{ 
    		get { return _termsRef_ListID; } 
    		set { SetProperty(ref _termsRef_ListID, value); } 
    	}
    
        private string _termsRef_FullName;
    	public string TermsRef_FullName 
    	{ 
    		get { return _termsRef_FullName; } 
    		set { SetProperty(ref _termsRef_FullName, value); } 
    	}
    
        private string _salesRepRef_ListID;
    	public string SalesRepRef_ListID 
    	{ 
    		get { return _salesRepRef_ListID; } 
    		set { SetProperty(ref _salesRepRef_ListID, value); } 
    	}
    
        private string _salesRepRef_FullName;
    	public string SalesRepRef_FullName 
    	{ 
    		get { return _salesRepRef_FullName; } 
    		set { SetProperty(ref _salesRepRef_FullName, value); } 
    	}
    
        private Nullable<decimal> _balance;
    	public Nullable<decimal> Balance 
    	{ 
    		get { return _balance; } 
    		set { SetProperty(ref _balance, value); } 
    	}
    
        private Nullable<decimal> _totalBalance;
    	public Nullable<decimal> TotalBalance 
    	{ 
    		get { return _totalBalance; } 
    		set { SetProperty(ref _totalBalance, value); } 
    	}
    
        private string _salesTaxCodeRef_ListID;
    	public string SalesTaxCodeRef_ListID 
    	{ 
    		get { return _salesTaxCodeRef_ListID; } 
    		set { SetProperty(ref _salesTaxCodeRef_ListID, value); } 
    	}
    
        private string _salesTaxCodeRef_FullName;
    	public string SalesTaxCodeRef_FullName 
    	{ 
    		get { return _salesTaxCodeRef_FullName; } 
    		set { SetProperty(ref _salesTaxCodeRef_FullName, value); } 
    	}
    
        private string _itemSalesTaxRef_ListID;
    	public string ItemSalesTaxRef_ListID 
    	{ 
    		get { return _itemSalesTaxRef_ListID; } 
    		set { SetProperty(ref _itemSalesTaxRef_ListID, value); } 
    	}
    
        private string _itemSalesTaxRef_FullName;
    	public string ItemSalesTaxRef_FullName 
    	{ 
    		get { return _itemSalesTaxRef_FullName; } 
    		set { SetProperty(ref _itemSalesTaxRef_FullName, value); } 
    	}
    
        private string _salesTaxCountry;
    	public string SalesTaxCountry 
    	{ 
    		get { return _salesTaxCountry; } 
    		set { SetProperty(ref _salesTaxCountry, value); } 
    	}
    
        private string _resaleNumber;
    	public string ResaleNumber 
    	{ 
    		get { return _resaleNumber; } 
    		set { SetProperty(ref _resaleNumber, value); } 
    	}
    
        private string _accountNumber;
    	public string AccountNumber 
    	{ 
    		get { return _accountNumber; } 
    		set { SetProperty(ref _accountNumber, value); } 
    	}
    
        private Nullable<decimal> _creditLimit;
    	public Nullable<decimal> CreditLimit 
    	{ 
    		get { return _creditLimit; } 
    		set { SetProperty(ref _creditLimit, value); } 
    	}
    
        private string _preferredPaymentMethodRef_ListID;
    	public string PreferredPaymentMethodRef_ListID 
    	{ 
    		get { return _preferredPaymentMethodRef_ListID; } 
    		set { SetProperty(ref _preferredPaymentMethodRef_ListID, value); } 
    	}
    
        private string _preferredPaymentMethodRef_FullName;
    	public string PreferredPaymentMethodRef_FullName 
    	{ 
    		get { return _preferredPaymentMethodRef_FullName; } 
    		set { SetProperty(ref _preferredPaymentMethodRef_FullName, value); } 
    	}
    
        private string _creditCardNumber;
    	public string CreditCardNumber 
    	{ 
    		get { return _creditCardNumber; } 
    		set { SetProperty(ref _creditCardNumber, value); } 
    	}
    
        private Nullable<int> _expirationMonth;
    	public Nullable<int> ExpirationMonth 
    	{ 
    		get { return _expirationMonth; } 
    		set { SetProperty(ref _expirationMonth, value); } 
    	}
    
        private Nullable<int> _expirationYear;
    	public Nullable<int> ExpirationYear 
    	{ 
    		get { return _expirationYear; } 
    		set { SetProperty(ref _expirationYear, value); } 
    	}
    
        private string _nameOnCard;
    	public string NameOnCard 
    	{ 
    		get { return _nameOnCard; } 
    		set { SetProperty(ref _nameOnCard, value); } 
    	}
    
        private string _creditCardAddress;
    	public string CreditCardAddress 
    	{ 
    		get { return _creditCardAddress; } 
    		set { SetProperty(ref _creditCardAddress, value); } 
    	}
    
        private string _creditCardPostalCode;
    	public string CreditCardPostalCode 
    	{ 
    		get { return _creditCardPostalCode; } 
    		set { SetProperty(ref _creditCardPostalCode, value); } 
    	}
    
        private string _jobStatus;
    	public string JobStatus 
    	{ 
    		get { return _jobStatus; } 
    		set { SetProperty(ref _jobStatus, value); } 
    	}
    
        private Nullable<System.DateTime> _jobStartDate;
    	public Nullable<System.DateTime> JobStartDate 
    	{ 
    		get { return _jobStartDate; } 
    		set { SetProperty(ref _jobStartDate, value); } 
    	}
    
        private Nullable<System.DateTime> _jobProjectedEndDate;
    	public Nullable<System.DateTime> JobProjectedEndDate 
    	{ 
    		get { return _jobProjectedEndDate; } 
    		set { SetProperty(ref _jobProjectedEndDate, value); } 
    	}
    
        private Nullable<System.DateTime> _jobEndDate;
    	public Nullable<System.DateTime> JobEndDate 
    	{ 
    		get { return _jobEndDate; } 
    		set { SetProperty(ref _jobEndDate, value); } 
    	}
    
        private string _jobDesc;
    	public string JobDesc 
    	{ 
    		get { return _jobDesc; } 
    		set { SetProperty(ref _jobDesc, value); } 
    	}
    
        private string _jobTypeRef_ListID;
    	public string JobTypeRef_ListID 
    	{ 
    		get { return _jobTypeRef_ListID; } 
    		set { SetProperty(ref _jobTypeRef_ListID, value); } 
    	}
    
        private string _jobTypeRef_FullName;
    	public string JobTypeRef_FullName 
    	{ 
    		get { return _jobTypeRef_FullName; } 
    		set { SetProperty(ref _jobTypeRef_FullName, value); } 
    	}
    
        private string _notes;
    	public string Notes 
    	{ 
    		get { return _notes; } 
    		set { SetProperty(ref _notes, value); } 
    	}
    
        private string _priceLevelRef_ListID;
    	public string PriceLevelRef_ListID 
    	{ 
    		get { return _priceLevelRef_ListID; } 
    		set { SetProperty(ref _priceLevelRef_ListID, value); } 
    	}
    
        private string _priceLevelRef_FullName;
    	public string PriceLevelRef_FullName 
    	{ 
    		get { return _priceLevelRef_FullName; } 
    		set { SetProperty(ref _priceLevelRef_FullName, value); } 
    	}
    
        private string _taxRegistrationNumber;
    	public string TaxRegistrationNumber 
    	{ 
    		get { return _taxRegistrationNumber; } 
    		set { SetProperty(ref _taxRegistrationNumber, value); } 
    	}
    
        private string _currencyRef_ListID;
    	public string CurrencyRef_ListID 
    	{ 
    		get { return _currencyRef_ListID; } 
    		set { SetProperty(ref _currencyRef_ListID, value); } 
    	}
    
        private string _currencyRef_FullName;
    	public string CurrencyRef_FullName 
    	{ 
    		get { return _currencyRef_FullName; } 
    		set { SetProperty(ref _currencyRef_FullName, value); } 
    	}
    
        private string _isStatementWithParent;
    	public string IsStatementWithParent 
    	{ 
    		get { return _isStatementWithParent; } 
    		set { SetProperty(ref _isStatementWithParent, value); } 
    	}
    
        private string _preferredDeliveryMethod;
    	public string PreferredDeliveryMethod 
    	{ 
    		get { return _preferredDeliveryMethod; } 
    		set { SetProperty(ref _preferredDeliveryMethod, value); } 
    	}
    
        private Nullable<System.DateTime> _customField3;
    	public Nullable<System.DateTime> CustomField3 
    	{ 
    		get { return _customField3; } 
    		set { SetProperty(ref _customField3, value); } 
    	}
    
        private string _customField4;
    	public string CustomField4 
    	{ 
    		get { return _customField4; } 
    		set { SetProperty(ref _customField4, value); } 
    	}
    
        private string _customField5;
    	public string CustomField5 
    	{ 
    		get { return _customField5; } 
    		set { SetProperty(ref _customField5, value); } 
    	}
    
        private string _customField6;
    	public string CustomField6 
    	{ 
    		get { return _customField6; } 
    		set { SetProperty(ref _customField6, value); } 
    	}
    
        private string _customField7;
    	public string CustomField7 
    	{ 
    		get { return _customField7; } 
    		set { SetProperty(ref _customField7, value); } 
    	}
    
        private string _customField8;
    	public string CustomField8 
    	{ 
    		get { return _customField8; } 
    		set { SetProperty(ref _customField8, value); } 
    	}
    
        private string _customField9;
    	public string CustomField9 
    	{ 
    		get { return _customField9; } 
    		set { SetProperty(ref _customField9, value); } 
    	}
    
        private string _customField10;
    	public string CustomField10 
    	{ 
    		get { return _customField10; } 
    		set { SetProperty(ref _customField10, value); } 
    	}
    
        private string _customField11;
    	public string CustomField11 
    	{ 
    		get { return _customField11; } 
    		set { SetProperty(ref _customField11, value); } 
    	}
    
        private string _customField12;
    	public string CustomField12 
    	{ 
    		get { return _customField12; } 
    		set { SetProperty(ref _customField12, value); } 
    	}
    
        private string _customField13;
    	public string CustomField13 
    	{ 
    		get { return _customField13; } 
    		set { SetProperty(ref _customField13, value); } 
    	}
    
        private string _customField14;
    	public string CustomField14 
    	{ 
    		get { return _customField14; } 
    		set { SetProperty(ref _customField14, value); } 
    	}
    
        private string _customField15;
    	public string CustomField15 
    	{ 
    		get { return _customField15; } 
    		set { SetProperty(ref _customField15, value); } 
    	}
    
        private string _status;
    	public string Status 
    	{ 
    		get { return _status; } 
    		set { SetProperty(ref _status, value); } 
    	}
    
        private string _birthday;
    	public string Birthday 
    	{ 
    		get { return _birthday; } 
    		set { SetProperty(ref _birthday, value); } 
    	}
    
        private string _text;
    	public string Text 
    	{ 
    		get { return _text; } 
    		set { SetProperty(ref _text, value); } 
    	}
    
    }
}
